# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eac446818048541bb19a665b184e19f457f9bd907050a88f2948a3f672497f4d9948d14f022620594bf9086a92e2b4d1ba633cfb8af8e5f8ce04a1547409d5a

test:
  secret_key_base: 75cf78635ac153ddbb927e2bcc445edce2b517d1c5540e02a662c78cb2826e4550c4f4c379d5d6a2459dd1b27fb62ab7bcdecd3353a19665fedc2be64f5e2905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
